# Generated by Django 5.2.8 on 2025-11-11 23:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("MODERATOR", "Moderator"),
                            ("DRIVER", "Driver"),
                            ("PUBLIC_USER", "Public User"),
                        ],
                        db_index=True,
                        default="PUBLIC_USER",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DiscountCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("SENIOR_CITIZEN", "Senior Citizen"),
                            ("PWD", "Person with Disability"),
                            ("STUDENT", "Student"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "id_image",
                    models.ImageField(
                        help_text="Upload ID image", upload_to="discount_cards/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        help_text="0.20 for 20% discount",
                        max_digits=4,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("daily_usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_discount_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("original_fare", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "discounted_fare",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("discount_rate", models.DecimalField(decimal_places=2, max_digits=4)),
                ("from_location", models.CharField(max_length=200)),
                ("to_location", models.CharField(max_length=200)),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=8,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "gps_coordinates",
                    models.JSONField(
                        blank=True, help_text="GPS coordinates {lat, lng}", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "discount_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="users.discountcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("OVERCHARGING", "Overcharging"),
                            ("REFUSAL_TO_CONVEY", "Refusal to Convey"),
                            ("RECKLESS_DRIVING", "Reckless Driving"),
                            ("VEHICLE_DEFECT", "Vehicle Defect"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=500)),
                (
                    "gps_coordinates",
                    models.JSONField(
                        blank=True, help_text="GPS coordinates {lat, lng}", null=True
                    ),
                ),
                (
                    "vehicle_info",
                    models.JSONField(
                        blank=True,
                        help_text="Vehicle details: plate number, type, color, etc.",
                        null=True,
                    ),
                ),
                (
                    "evidence_files",
                    models.JSONField(
                        blank=True, default=list, help_text="Array of file URLs"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("vehicle_type", models.CharField(max_length=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("registration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FareCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_location", models.CharField(max_length=500)),
                ("to_location", models.CharField(max_length=500)),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=8,
                    ),
                ),
                (
                    "calculated_fare",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "actual_fare",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "original_fare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fare before discount",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "discount_applied",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("discount_type", models.CharField(blank=True, max_length=50)),
                (
                    "calculation_type",
                    models.CharField(
                        help_text="Method used: Google Maps Route Planner, GPS, Smart Calculator, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "route_data",
                    models.JSONField(
                        blank=True,
                        help_text="Stores polyline, barangay info, waypoints, etc.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "discount_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_calculations",
                        to="users.discountcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fare_calculations",
                        to="users.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_user_role_e1ec1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcard",
            index=models.Index(
                fields=["user", "verification_status"],
                name="users_disco_user_id_f255d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountcard",
            index=models.Index(
                fields=["is_active", "verification_status"],
                name="users_disco_is_acti_4c09d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountcard",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="users_disco_valid_f_75ea62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="discountusagelog",
            index=models.Index(
                fields=["discount_card", "created_at"],
                name="users_disco_discoun_b82ba6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "priority"], name="users_incid_status_3d9c48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["incident_type", "status"],
                name="users_incid_inciden_531815_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["user", "created_at"], name="users_incid_user_id_1ecbd2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farecalculation",
            index=models.Index(
                fields=["user", "created_at"], name="users_farec_user_id_1d90cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farecalculation",
            index=models.Index(
                fields=["calculation_type"], name="users_farec_calcula_f1f35e_idx"
            ),
        ),
    ]
