# Generated by Django 5.2.8 on 2025-11-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular"),
                            ("STUDENT", "Student"),
                            ("SENIOR", "Senior Citizen"),
                            ("PWD", "Person with Disability"),
                            ("CHILD", "Child"),
                        ],
                        default="REGULAR",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fares",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "passenger_type"],
            },
        ),
    ]
