# Generated by Django 5.2.8 on 2025-11-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BARANGAY", "Barangay"),
                            ("LANDMARK", "Landmark"),
                            ("SITIO", "Sitio"),
                            ("POBLACION", "Poblacion"),
                        ],
                        db_index=True,
                        default="BARANGAY",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("barangay", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "boundary_data",
                    models.JSONField(
                        blank=True, help_text="GeoJSON polygon coordinates", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["type", "is_active"], name="locations_l_type_7239b8_idx"
                    ),
                    models.Index(
                        fields=["barangay"], name="locations_l_baranga_107f6a_idx"
                    ),
                ],
            },
        ),
    ]
